[workspace]
members = [
    "crates/interner",
    "crates/verifier-core",
    "crates/verifier-driver",
    "crates/verifier-rustc", "play",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
bumpalo = "3.20.3"
hashbrown = "0.17.1"
index_vec = "0.1.4"
smallvec = { version = "1", features = ["const_generics"] }
fixedbitset = "0.5.7"
generative-scoped-tls = { git = "https://github.com/sssxks/generative-scoped-tls", rev = "3c7796dffb0671fc646420e2be646c58965b9710" }
interner = { path = "crates/interner" }
verifier-core = { path = "crates/verifier-core" }
verifier-rustc = { path = "crates/verifier-rustc" }
