[package]
name = "verifier-core"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
fixedbitset = { workspace = true }
generative-scoped-tls = { workspace = true }
hashbrown = { workspace = true }
index_vec = { workspace = true }
smallvec = { workspace = true }
interner = { workspace = true }
